In [ ]:
n = int(input("Enter a number: "))
c = 0
for i in range(1, n+1):
  if n%i == 0:
    c = c+1
if c == 2:
  print(n,'is a Prime')
else:
  print(n,'is Non Prime')

Enter a number: 6
6 is Non Prime


In [ ]:
def fib(n):
  if n==0 or n==1:
    return n
  else:
    return fib(n-1)+fib(n-2)
x=int(input("Enter a number: "))
for i in range(x):
  print(fib(i))



Enter a number: 5
0 	
1 	
1 	
2 	
3 	


In [ ]:
def gcd(a,b):
  while b:
    a,b=b,a%b
  return a
def lcm(a,b):
  return int((a*b)/gcd(a,b))
a=int(input('enter 1st number:'))
b=int(input('enter 2nd number:'))
print('GCD:',gcd(a,b))
print('LCM:',lcm(a,b))


enter 1st number:12
enter 2nd number:15
GCD: 3
LCM: 60


In [12]:
def add(x,y):
  return x + y

def sub(x,y):
  return x - y

def mult(x,y):
  return x * y

def div(x,y):
  if y==0:
    return "Error in division!"
  else:
    return x / y



def calculator():
  print("Enter the operation:")
  print("1.Add")
  print("2.Subtract")
  print("3.Multiply")
  print("4.Division")
  ops=input()
  a=int(input("Enter 1st number:"))
  b=int(input("Enter 2nd number:"))
  if ops=='1':
    print(f"Result= {add(a,b)}")
  elif ops=='2':
    print(f"Result= {sub(a,b)}")
  elif ops=='3':
    print(f"Result= {mult(a,b)}")
  elif ops=='4':
    print(f"Result= {div(a,b)}")
  else:
    print("Invalid!")

calculator()


Enter the operation:
1.Add
2.Subtract
3.Multiply
4.Division
4
Enter 1st number:3
Enter 2nd number:1
Result= 3.0


In [34]:
a=[]
n=int(input("enter number of elements:"))
for i in range(n):
  b=input()
  a.append(b)
a=set(a)
a=list(a)
print(a)

enter number of elements:5
1
2
3
2
3
['1', '2', '3']


In [14]:
dic= {}
dic["name"]="Dineep"
dic["age"]=25
dic["city"]="Hyderabad"
dic["qualification"]="Btech"
dic["department"]="AIML"

for key,value in dic.items():
  print(f"{key} = {value}")

name = Dineep
age = 25
city = Hyderabad
qualification = Btech
department = AIML


In [18]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[4,3],[2,1]])
print("Addition of matrices:\n",A+B)
print("Subtraction of matrices:\n",A-B)
print("Multiplation of matrices:\n",A*B)
print("Transpose of matrix A:\n",A.T)
print("Transpose of matrix B:\n",B.T)

Addition of matrices:
 [[5 5]
 [5 5]]
Subtraction of matrices:
 [[-3 -1]
 [ 1  3]]
Multiplation of matrices:
 [[4 6]
 [6 4]]
Transpose of matrix A:
 [[1 3]
 [2 4]]
Transpose of matrix B:
 [[4 2]
 [3 1]]


In [25]:
import pandas as pd
df = pd.read_csv("p.csv")
print(df.head(5))

   S.No Roll no
0     1      G1
1     2      G2
2     3      G3
3     4      G4
4     5      G5


In [30]:
from collections import Counter

def most_common_word(text):
    words = text.lower().split()
    word_counts = Counter(words)
    most_common = word_counts.most_common(1)
    return most_common[0] if most_common else none

word, count = most_common_word(text)
print(f"The most common word is '{word}' with {count} occurrences.")


The most common word is 'orange' with 4 occurrences.


In [31]:
import random
import string

def generate_password(length=8):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

print(generate_password(5))

9&F8h
